### ISSUE TITLE
About your plan on water storage estimation

### ISSUE THREAD

**Issue by scarlettlee** [davemlz/water-storage-retrieval#1]
Hello David,

I'm Huan Li who has attended the lightning talks in G4G2020, and listened to your excellent work on water storage retrieval. Has your work in this page published? 

I'm also very curious about your plan on this work. Let's keep in touch. My email is huan.li@pku.edu.cn. How about yours?

Best Regards,

Huan Li

**Comment by davemlz** [comment]
Hello, Huan Li,

Thank you very much for attending the lightning talk! The work isn't
published yet, but it is in process.

Sure! Right now we're trying to improve our models to estimate bathymetry,
but this time using CNNs instead of ensembles methods. I hope to have the
results published soon!

My e-mail is dml.mont@gmail.com. Feel free to contact me anytime!

Best Regards,

*David Montero Loaiza*
Master in Data Science | Topographic Engineer
Teléfono: +573163215234
e-mail: *dml.mont@gmail.com* <dml.mont@gmail.com>
